services:
  ##### Managed Services #####
  qdrant:
    container_name: qdrant_container
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./docekr/dbs/qdrant:/qdrant/storage
  ##### Services #####
  knowledge-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - "QDRANT_URL=http://localhost:6333"
      - "QDRANT_API_KEY=${QDRANT_API_KEY}"
      - "ACCESS_TOKEN=${ACCESS_TOKEN}"
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"
    volumes:
      - .:/app
    # depends_on:
    #   - qdrant